#Build the web app and push to Firebase Hosting Target 'prod'

name: Deploy to Production
on:
  push:
    branches:
      - master
jobs:
  build_web:
    name: Build Flutter Web
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:latest
    steps:
      - uses: actions/checkout@v2
      - run : flutter build web
      - name: Tar files
        run: tar -cvf build_web.tar build/web
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-web
          path: build_web.tar
          retention-days: 1

  deploy:
    name: Deploy to Firebase Hosting
    needs : build_web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Previously Built Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-web
          path: build/
      - name: Extract Tar files
        run: tar -xvf build/build_web.tar
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AKSHAY_MUNDOTIA }}'
          projectId: akshay-mundotia
          target: prod
          channelId: live


