#Build the web app and push to Firebase Hosting Target 'staging'

name: Deploy to Production
on:
  push:
    branches:
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:latest
    steps:
      - uses: actions/checkout@v2
      - run : flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AKSHAY_MUNDOTIA }}'
          projectId: akshay-mundotia
          target: staging


